// This file is auto-generated by scripts/update-maxpreps-players.mjs
// Contains MaxPreps player roster data for CCS teams

export interface Player {
  id: string;
  name: string;
  position: string;
  number: number | null;
  team: string;
  grade: string | null;
  height: string | null;
  weight: string | null;
}

// Sample player data - would be populated from MaxPreps rosters
export const players: Player[] = [
  {
    id: "archbishop-riordan-1",
    name: "Sample Player",
    position: "Quarterback",
    number: 7,
    team: "archbishop-riordan",
    grade: "Senior",
    height: "6'2\"",
    weight: "200",
  },
  {
    id: "archbishop-riordan-2",
    name: "Another Player",
    position: "Wide Receiver",
    number: 11,
    team: "archbishop-riordan",
    grade: "Junior",
    height: "6'0\"",
    weight: "185",
  },
  {
    id: "junipero-serra-1",
    name: "Serra Player",
    position: "Running Back",
    number: 3,
    team: "junipero-serra",
    grade: "Senior",
    height: "5'10\"",
    weight: "200",
  },
];
